### ISSUE TITLE
PyTorch>=0.5 compatibility data[0] to data.item()

### ISSUE THREAD

**Issue by ogencoglu** [Xiaoming-Yu/SingleGAN#10]
Thank you for this work.

This version gives the following error with recent PyTorch versions:
`IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
` 
as the index of 0-dim tensor is invalid since PyTorch>0.5 if I remember correctly.

 Fix: All `data[0]`s in _single_gan.py_ - `get_current_errors` function needs to be changed to `data.item()`.

Cheers!

**Comment by Xiaoming-Yu** [comment]
Thanks for your reminder. I have updated the code.

Best Wishes！
