### ISSUE TITLE
Color transformation during day2night translation 

### ISSUE THREAD

**Issue by OrGreenberg** [Xiaoming-Yu/SingleGAN#11]
Thanks for both the paper the the implementation. I found it clever and interesting. 
Well done and Well written!

I trained the model for a day2night translation using bdd100k dataset and the results looks quite good.
Unfortunately, I ran into some unplanned color transformation phenomena. 
See attached image of "night to day" translation as an example, where green traffic lights turned unfortunately red.. 

![image](https://user-images.githubusercontent.com/73229978/171182305-1c0a020e-3390-4f87-b3b5-cb61834757af.png)
[https://user-images.githubusercontent.com/73229978/171182305-1c0a020e-3390-4f87-b3b5-cb61834757af.png](url)

This phenomena of color transformation is repeating through the whole test set (red<->green, yellow<->purple etc.)
Do you have any clue or suggestion?

Thx!
Or

**Comment by Xiaoming-Yu** [comment]
Sorry for the late reply.
The color transformation may be caused by the cycle consistency, as the NN wants to preseve some visual cues to recover the source image. You can try to adjust the weight for cycle loss or replace it with the reconstruction loss.
