### ISSUE TITLE
Cannot start training on linux machine

### ISSUE THREAD

**Issue by stoneyang** [Xiaoming-Yu/SingleGAN#2]
Hi, @Xiaoming-Yu, 

Thanks for your work and code! It's amazing! 

Unfortunately, when running this `bash ./scripts/train_base.sh apple2orange` as stated in README. Error message like the following appears:
```
Traceback (most recent call last):
  File "./train.py", line 9, in <module>
    opt = TrainOptions().parse()
  File "/xxx/SingleGAN/options/base_options.py", line 57, in parse
    if not continue_train:
NameError: name 'continue_train' is not defined
```
Any suggestions? Thanks again, and in advance.

**Comment by stoneyang** [comment]
**Correct my if you find any error in the following statement**: 
It seems to me that you inherit `TrainOptions` from `BaseOptions`, while variable `continue_train` is declared in `TrainOptions`.

**Comment by Xiaoming-Yu** [comment]
Thanks for your comment. We have fixed this bug.
This error is caused by the wrong use of undeclared variable:
` continue_train` -> `self.opt.continue_train`

**Comment by stoneyang** [comment]
> Thanks for your comment. We have fixed this bug.
> This error is caused by the wrong use of undeclared variable:
> ` continue_train` -> `self.opt.continue_train`

That's it, thanks for your timely reply.
