### ISSUE TITLE
Confusion about the code

### ISSUE THREAD

**Issue by o0t1ng0o** [Xiaoming-Yu/SingleGAN#6]
Hi, @Xiaoming-Yu !

Although i have read your paper, i still am still confused about the meaning of the following codes.
https://github.com/Xiaoming-Yu/SingleGAN/blob/1b64893f6b35e84f73335c626bfb3b70aea1fdf1/models/single_gan.py#L194
What's the meaning of `c_enc, mu` and `logvar` resepctively ?
I think that the `c_enc` acts like the style latent code to enhance the variation.
Am i right?

**Comment by Xiaoming-Yu** [comment]
Yes, the latent code  `c_enc ` indicates the target style of the generated image.
As we state in the paper, this version of `SingleGAN` can consider as an unsupervised version of [BicycleGAN ](https://github.com/junyanz/BicycleGAN) with a single generator.

**Comment by o0t1ng0o** [comment]
How about the meaning of `mu` and `logvar`?

**Comment by Xiaoming-Yu** [comment]
Since we assume the latent code can be modeled by Gaussian priors, we use the VAE-like encoder to extract the target latent code.
`mu` and `logvar` are the predicted mean and (log)variance of  the style(distribution).

**Comment by o0t1ng0o** [comment]
Thanks for your reply!!
