### ISSUE TITLE
The cat to dog experiment results are very poor, how do you understand?

### ISSUE THREAD

**Issue by c1a1o1** [Xiaoming-Yu/SingleGAN#8]
The cat to dog experiment results are very poor, how do you understand?

**Comment by Xiaoming-Yu** [comment]
Could you tell me more details of the cat2dog experiment? Such as  dataset and training settings.
The dataset used in this experiment are form [DRIT](https://github.com/HsinYingLee/DRIT/blob/master/datasets/download_dataset.sh) and the model is equipped with Spectral Normalization.

**Comment by c1a1o1** [comment]
Thanks, I will try it!

**Comment by Xiaoming-Yu** [comment]
Don't  mention it.
Acturally, It is difficult to translate between domains with  very different semantics (especially the structure).
